In [1]:
import pandas as pd
pd.read_parquet("../data/bronze/currencies")

,id,name,short_code,code,precision,subunit,symbol,symbol_first,decimal_mark,thousands_separator,_ingested_at,_source_file,_batch_id
0,1,UAE Dirham,AED,784,2,100,د.إ,True,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
1,2,Afghani,AFN,971,2,100,؋,False,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
2,3,Lek,ALL,8,2,100,L,False,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
3,4,Armenian Dram,AMD,51,2,100,դր.,False,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
4,5,Netherlands Antillean Guilder,ANG,532,2,100,ƒ,True,",",.,2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,157,CFP Franc,XPF,953,0,1,Fr,False,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
157,158,Yemeni Rial,YER,886,2,100,﷼,False,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
158,159,Rand,ZAR,710,2,100,R,True,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
159,160,Zambian Kwacha,ZMW,967,2,100,ZK,False,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
160,161,Zimbabwe Dollar,ZWL,932,2,100,$,True,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632

In [4]:
import pandas as pd
pd.read_parquet("../data/bronze/rates")

,currency,rate,rate_date,_ingested_at,_source_file,_batch_id,curr_base
0,LSL,4.5620793700,2026-03-19 19:20:04,2026-03-19 19:20:27.146804,https://api.currencybeacon.com/v1/latest,20260319_192026,AED
1,UGX,1028.4990505800,2026-03-19 19:20:04,2026-03-19 19:20:27.146804,https://api.currencybeacon.com/v1/latest,20260319_192026,AED
2,GTQ,2.0876725200,2026-03-19 19:20:04,2026-03-19 19:20:27.146804,https://api.currencybeacon.com/v1/latest,20260319_192026,AED
3,GNF,2388.8344569700,2026-03-19 19:20:04,2026-03-19 19:20:27.146804,https://api.currencybeacon.com/v1/latest,20260319_192026,AED
4,SHP,0.2026639100,2026-03-19 19:20:04,2026-03-19 19:20:27.146804,https://api.currencybeacon.com/v1/latest,20260319_192026,AED
...,...,...,...,...,...,...,...
25595,SVC,0.0001384300,2026-03-19 19:20:02,2026-03-19 19:20:27.146804,https://api.currencybeacon.com/v1/latest,20260319_192026,ZWL
25596,SAR,0.0000593300,2026-03-19 19:20:02,2026-03-19 19:20:27.146804,https://api.currencybeacon.com/v1/latest,20260319_192026,ZWL
25597,NGN,0.0214994400,2026-03-19 19:20:02,2026-03-19 19:20:27.146804,https://api.currencybeacon.com/v1/latest,20260319_192026,ZWL
25598,CRC,0.0074073200,2026-03-19 19:20:02,2026-03-19 19:20:27.146804,https://api.currencybeacon.com/v1/latest,20260319_192026,ZWL
25599,VUV,0.0018838300,2026-03-19 19:20:02,2026-03-19 19:20:27.146804,https://api.currencybeacon.com/v1/latest,20260319_192026,ZWL

In [4]:
import pandas as pd
pd.read_parquet("../data/silver/currencies")

,id,name,short_code,code,precision,subunit,symbol,symbol_first,decimal_mark,thousands_separator,_ingested_at,_source_file,_batch_id
0,1,UAE Dirham,AED,784,2,100,د.إ,True,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
1,2,Afghani,AFN,971,2,100,؋,False,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
2,3,Lek,ALL,008,2,100,L,False,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
3,4,Armenian Dram,AMD,051,2,100,դր.,False,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
4,5,Netherlands Antillean Guilder,ANG,532,2,100,ƒ,True,",",.,2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,157,CFP Franc,XPF,953,0,1,Fr,False,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
157,158,Yemeni Rial,YER,886,2,100,ریال,False,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
158,159,Rand,ZAR,710,2,100,R,True,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
159,160,Zambian Kwacha,ZMW,967,2,100,ZK,False,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632
160,161,Zimbabwe Dollar,ZWL,932,2,100,$,True,.,",",2026-03-19 10:06:34.854603,https://api.currencybeacon.com/v1/currencies,20260319_100632

In [7]:
import os
import pandas as pd

if os.path.exists('../data/silver/currencies_quarantine'):
    pd.read_parquet('../data/silver/currencies_quarantine')
else:
    print('No currency quarantine data')

No currency quarantine data